# Generated by Django 4.2.10 on 2025-03-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('calculation_type', models.CharField(choices=[('rescisao', 'Rescisão'), ('ferias', 'Férias'), ('horas_extras', 'Horas Extras'), ('insalubridade', 'Insalubridade'), ('periculosidade', 'Periculosidade'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de Cálculo')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nome do Cliente')),
                ('client_document', models.CharField(max_length=20, verbose_name='Documento do Cliente')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('in_progress', 'Em Andamento'), ('review', 'Em Revisão'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Status')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor do Cálculo')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='services/attachments/%Y/%m/', verbose_name='Anexos')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Prazo')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ['-created_at'],
            },
        ),
    ]
