# Generated by Django 4.2.10 on 2025-03-14 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0003_remove_service_client_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTypeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Base')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('status', models.BooleanField(default=True, verbose_name='Ativo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_types', to='services.client', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_service_types_client', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Tipo de Serviço por Cliente',
                'verbose_name_plural': 'Tipos de Serviço por Cliente',
                'ordering': ['-created_at'],
            },
        ),
    ]
