# Generated by Django 4.2.10 on 2025-03-14 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicetypeclient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.servicetypeclient', verbose_name='Tipo de Serviço'),
        ),
    ]
