# Generated by Django 4.2.10 on 2025-03-14 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_service_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicetypeclient',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tipo de Serviço', 'verbose_name_plural': 'Tipos de Serviço'},
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
